AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create input S3 bucket.'

Parameters:
    S3BucketName:
        Type: String
        Description: "S3 input bucket name. (Note: AWS Region name and Account ID are automatically added as suffices of the bucket name)"
        Default: "activity-detection-data-bucket"
        
Resources:
    MyBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub "${S3BucketName}-${AWS::Region}-${AWS::AccountId}"
